export const INDEX_BRANDS = 'INDEX_BRANDS';
export const INDEX_BRANDS_SUCCESS = 'INDEX_BRANDS_SUCCESS';
export const INDEX_BRANDS_FAIL = 'INDEX_BRANDS_FAIL';

export const CREATE_ONE_BRAND = 'CREATE_ONE_BRAND';
export const CREATE_ONE_BRAND_SUCCESS = 'CREATE_ONE_BRAND_SUCCESS';
export const CREATE_ONE_BRAND_FAIL = 'CREATE_ONE_BRAND_FAIL';

export const UPDATE_ONE_BRAND = 'UPDATE_ONE_BRAND';
export const UPDATE_ONE_BRAND_SUCCESS = 'UPDATE_ONE_BRAND_SUCCESS';
export const UPDATE_ONE_BRAND_FAIL = 'UPDATE_ONE_BRAND_FAIL';

export const DELETE_ONE_BRAND = 'DELETE_ONE_BRAND';
export const DELETE_ONE_BRAND_SUCCESS = 'DELETE_ONE_BRAND_SUCCESS';
export const DELETE_ONE_BRAND_FAIL = 'DELETE_ONE_BRAND_FAIL';

export const INDEX_MANUFACTURERS = 'INDEX_MANUFACTURERS';
export const INDEX_MANUFACTURERS_SUCCESS = 'INDEX_MANUFACTURERS_SUCCESS';
export const INDEX_MANUFACTURERS_FAIL = 'INDEX_MANUFACTURERS_FAIL';

export const CREATE_ONE_MANUFACTURER = 'CREATE_ONE_MANUFACTURER';
export const CREATE_ONE_MANUFACTURER_SUCCESS = 'CREATE_ONE_MANUFACTURER_SUCCESS';
export const CREATE_ONE_MANUFACTURER_FAIL = 'CREATE_ONE_MANUFACTURER_FAIL';

export const UPDATE_ONE_MANUFACTURER = 'UPDATE_ONE_MANUFACTURER';
export const UPDATE_ONE_MANUFACTURER_SUCCESS = 'UPDATE_ONE_MANUFACTURER_SUCCESS';
export const UPDATE_ONE_MANUFACTURER_FAIL = 'UPDATE_ONE_MANUFACTURER_FAIL';

export const DELETE_ONE_MANUFACTURER = 'DELETE_ONE_MANUFACTURER';
export const DELETE_ONE_MANUFACTURER_SUCCESS = 'DELETE_ONE_MANUFACTURER_SUCCESS';
export const DELETE_ONE_MANUFACTURER_FAIL = 'DELETE_ONE_MANUFACTURER_FAIL';



export const INDEX_BRANCHES = 'INDEX_BRANCHES';
export const INDEX_BRANCHES_SUCCESS = 'INDEX_BRANCHES_SUCCESS';
export const INDEX_BRANCHES_FAIL = 'INDEX_BRANCHES_FAIL';

export const CREATE_ONE_BRANCH = 'CREATE_ONE_BRANCH';
export const CREATE_ONE_BRANCH_SUCCESS = 'CREATE_ONE_BRANCH_SUCCESS';
export const CREATE_ONE_BRANCH_FAIL = 'CREATE_ONE_BRANCH_FAIL';

export const UPDATE_ONE_BRANCH = 'UPDATE_ONE_BRANCH';
export const UPDATE_ONE_BRANCH_SUCCESS = 'UPDATE_ONE_BRANCH_SUCCESS';
export const UPDATE_ONE_BRANCH_FAIL = 'UPDATE_ONE_BRANCH_FAIL';

export const DELETE_ONE_BRANCH = 'DELETE_ONE_BRANCH';
export const DELETE_ONE_BRANCH_SUCCESS = 'DELETE_ONE_BRANCH_SUCCESS';
export const DELETE_ONE_BRANCH_FAIL = 'DELETE_ONE_BRANCH_FAIL';

export const INDEX_BUSINESS_CATEGORIES = 'INDEX_BUSINESS_CATEGORIES';
export const INDEX_BUSINESS_CATEGORIES_SUCCESS = 'INDEX_BUSINESS_CATEGORIES_SUCCESS';
export const INDEX_BUSINESS_CATEGORIES_FAIL = 'INDEX_BUSINESS_CATEGORIES_FAIL';

export const CREATE_ONE_BUSINESS_CATEGORY = 'CREATE_ONE_BUSINESS_CATEGORY';
export const CREATE_ONE_BUSINESS_CATEGORY_SUCCESS = 'CREATE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const CREATE_ONE_BUSINESS_CATEGORY_FAIL = 'CREATE_ONE_BUSINESS_CATEGORY_FAIL';

export const UPDATE_ONE_BUSINESS_CATEGORY = 'UPDATE_ONE_BUSINESS_CATEGORY';
export const UPDATE_ONE_BUSINESS_CATEGORY_SUCCESS = 'UPDATE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const UPDATE_ONE_BUSINESS_CATEGORY_FAIL = 'UPDATE_ONE_BUSINESS_CATEGORY_FAIL';

export const DELETE_ONE_BUSINESS_CATEGORY = 'DELETE_ONE_BUSINESS_CATEGORY';
export const DELETE_ONE_BUSINESS_CATEGORY_SUCCESS = 'DELETE_ONE_BUSINESS_CATEGORY_SUCCESS';
export const DELETE_ONE_BUSINESS_CATEGORY_FAIL = 'DELETE_ONE_BUSINESS_CATEGORY_FAIL';

export const INDEX_PRODUCT_CATEGORIES = 'INDEX_PRODUCT_CATEGORIES';
export const INDEX_PRODUCT_CATEGORIES_SUCCESS = 'INDEX_PRODUCT_CATEGORIES_SUCCESS';
export const INDEX_PRODUCT_CATEGORIES_FAIL = 'INDEX_PRODUCT_CATEGORIES_FAIL';

export const CREATE_ONE_PRODUCT_CATEGORY = 'CREATE_ONE_PRODUCT_CATEGORY';
export const CREATE_ONE_PRODUCT_CATEGORY_SUCCESS = 'CREATE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const CREATE_ONE_PRODUCT_CATEGORY_FAIL = 'CREATE_ONE_PRODUCT_CATEGORY_FAIL';

export const UPDATE_ONE_PRODUCT_CATEGORY = 'UPDATE_ONE_PRODUCT_CATEGORY';
export const UPDATE_ONE_PRODUCT_CATEGORY_SUCCESS = 'UPDATE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_ONE_PRODUCT_CATEGORY_FAIL = 'UPDATE_ONE_PRODUCT_CATEGORY_FAIL';

export const DELETE_ONE_PRODUCT_CATEGORY = 'DELETE_ONE_PRODUCT_CATEGORY';
export const DELETE_ONE_PRODUCT_CATEGORY_SUCCESS = 'DELETE_ONE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_ONE_PRODUCT_CATEGORY_FAIL = 'DELETE_ONE_PRODUCT_CATEGORY_FAIL';

export const INDEX_PRODUCTS = 'INDEX_PRODUCTS';
export const INDEX_PRODUCTS_SUCCESS = 'INDEX_PRODUCTS_SUCCESS';
export const INDEX_PRODUCTS_FAIL = 'INDEX_PRODUCTS_FAIL';

export const CREATE_ONE_PRODUCT = 'CREATE_ONE_PRODUCT';
export const CREATE_ONE_PRODUCT_SUCCESS = 'CREATE_ONE_PRODUCT_SUCCESS';
export const CREATE_ONE_PRODUCT_FAIL = 'CREATE_ONE_PRODUCT_FAIL';

export const UPDATE_ONE_PRODUCT = 'UPDATE_ONE_PRODUCT';
export const UPDATE_ONE_PRODUCT_SUCCESS = 'UPDATE_ONE_PRODUCT_SUCCESS';
export const UPDATE_ONE_PRODUCT_FAIL = 'UPDATE_ONE_PRODUCT_FAIL';

export const DELETE_ONE_PRODUCT = 'DELETE_ONE_PRODUCT';
export const DELETE_ONE_PRODUCT_SUCCESS = 'DELETE_ONE_PRODUCT_SUCCESS';
export const DELETE_ONE_PRODUCT_FAIL = 'DELETE_ONE_PRODUCT_FAIL';

export const INDEX_COUNTRIES = 'INDEX_COUNTRIES';
export const INDEX_COUNTRIES_SUCCESS = 'INDEX_COUNTRIES_SUCCESS';
export const INDEX_COUNTRIES_FAIL = 'INDEX_COUNTRIES_FAIL';

export const CREATE_ONE_COUNTRY = 'CREATE_ONE_COUNTRY';
export const CREATE_ONE_COUNTRY_SUCCESS = 'CREATE_ONE_COUNTRY_SUCCESS';
export const CREATE_ONE_COUNTRY_FAIL = 'CREATE_ONE_COUNTRY_FAIL';

export const UPDATE_ONE_COUNTRY = 'UPDATE_ONE_COUNTRY';
export const UPDATE_ONE_COUNTRY_SUCCESS = 'UPDATE_ONE_COUNTRY_SUCCESS';
export const UPDATE_ONE_COUNTRY_FAIL = 'UPDATE_ONE_COUNTRY_FAIL';

export const DELETE_ONE_COUNTRY= 'DELETE_ONE_COUNTRY';
export const DELETE_ONE_COUNTRY_SUCCESS = 'DELETE_ONE_COUNTRY_SUCCESS';
export const DELETE_ONE_COUNTRY_FAIL = 'DELETE_ONE_COUNTRY_FAIL';

export const INDEX_REGIONS = 'INDEX_REGIONS';
export const INDEX_REGIONS_SUCCESS = 'INDEX_REGIONS_SUCCESS';
export const INDEX_REGIONS_FAIL = 'INDEX_REGIONS_FAIL';

export const CREATE_ONE_REGION = 'CREATE_ONE_REGION';
export const CREATE_ONE_REGION_SUCCESS = 'CREATE_ONE_REGION_SUCCESS';
export const CREATE_ONE_REGION_FAIL = 'CREATE_ONE_REGION_FAIL';

export const UPDATE_ONE_REGION = 'UPDATE_ONE_REGION';
export const UPDATE_ONE_REGION_SUCCESS = 'UPDATE_ONE_REGION_SUCCESS';
export const UPDATE_ONE_REGION_FAIL = 'UPDATE_ONE_REGION_FAIL';

export const DELETE_ONE_REGION = 'DELETE_ONE_REGION';
export const DELETE_ONE_REGION_SUCCESS = 'DELETE_ONE_REGION_SUCCESS';
export const DELETE_ONE_REGION_FAIL = 'DELETE_ONE_REGION_FAIL';

export const INDEX_COMPANIES = 'INDEX_COMPANIES';
export const INDEX_COMPANIES_SUCCESS = 'INDEX_COMPANIES_SUCCESS';
export const INDEX_COMPANIES_FAIL = 'INDEX_COMPANIES_FAIL';

export const CREATE_ONE_COMPANY = 'CREATE_ONE_COMPANY';
export const CREATE_ONE_COMPANY_SUCCESS = 'CREATE_ONE_COMPANY_SUCCESS';
export const CREATE_ONE_COMPANY_FAIL = 'CREATE_ONE_COMPANY_FAIL';

export const UPDATE_ONE_COMPANY = 'UPDATE_ONE_COMPANY';
export const UPDATE_ONE_COMPANY_SUCCESS = 'UPDATE_ONE_COMPANY_SUCCESS';
export const UPDATE_ONE_COMPANY_FAIL = 'UPDATE_ONE_COMPANY_FAIL';

export const DELETE_ONE_COMPANY = 'DELETE_ONE_COMPANY';
export const DELETE_ONE_COMPANY_SUCCESS = 'DELETE_ONE_COMPANY_SUCCESS';
export const DELETE_ONE_COMPANY_FAIL = 'DELETE_ONE_COMPANY_FAIL';

export const INDEX_USERS = 'INDEX_USERS';
export const INDEX_USERS_SUCCESS = 'INDEX_USERS_SUCCESS';
export const INDEX_USERS_FAIL = 'INDEX_USERS_FAIL';

export const CREATE_ONE_USER = 'CREATE_ONE_USER';
export const CREATE_ONE_USER_SUCCESS = 'CREATE_ONE_USER_SUCCESS';
export const CREATE_ONE_USER_FAIL = 'CREATE_ONE_USER_FAIL';

export const UPDATE_ONE_USER = 'UPDATE_ONE_USER';
export const UPDATE_ONE_USER_SUCCESS = 'UPDATE_ONE_USER_SUCCESS';
export const UPDATE_ONE_USER_FAIL = 'UPDATE_ONE_USER_FAIL';

export const DELETE_ONE_USER = 'DELETE_ONE_USER';
export const DELETE_ONE_USER_SUCCESS = 'DELETE_ONE_USER_SUCCESS';
export const DELETE_ONE_USER_FAIL = 'DELETE_ONE_USER_FAIL';

export const INDEX_TOWNS = 'INDEX_TOWNS';
export const INDEX_TOWNS_SUCCESS = 'INDEX_TOWNS_SUCCESS';
export const INDEX_TOWNS_FAIL = 'INDEX_TOWNS_FAIL';

export const CREATE_ONE_TOWN = 'CREATE_ONE_TOWN';
export const CREATE_ONE_TOWN_SUCCESS = 'CREATE_ONE_TOWN_SUCCESS';
export const CREATE_ONE_TOWN_FAIL = 'CREATE_ONE_TOWN_FAIL';

export const UPDATE_ONE_TOWN = 'UPDATE_ONE_TOWN';
export const UPDATE_ONE_TOWN_SUCCESS = 'UPDATE_ONE_TOWN_SUCCESS';
export const UPDATE_ONE_TOWN_FAIL = 'UPDATE_ONE_TOWN_FAIL';

export const DELETE_ONE_TOWN = 'DELETE_ONE_TOWN';
export const DELETE_ONE_TOWN_SUCCESS = 'DELETE_ONE_TOWN_SUCCESS';
export const DELETE_ONE_TOWN_FAIL = 'DELETE_ONE_TOWN_FAIL';

export const INDEX_COMMUNITIES = 'INDEX_COMMUNITIES';
export const INDEX_COMMUNITIES_SUCCESS = 'INDEX_COMMUNITIES_SUCCESS';
export const INDEX_COMMUNITIES_FAIL = 'INDEX_COMMUNITIES_FAIL';

export const CREATE_ONE_COMMUNITY = 'CREATE_ONE_COMMUNITY';
export const CREATE_ONE_COMMUNITY_SUCCESS = 'CREATE_ONE_COMMUNITY_SUCCESS';
export const CREATE_ONE_COMMUNITY_FAIL = 'CREATE_ONE_COMMUNITY_FAIL';

export const UPDATE_ONE_COMMUNITY = 'UPDATE_ONE_COMMUNITY';
export const UPDATE_ONE_COMMUNITY_SUCCESS = 'UPDATE_ONE_COMMUNITY_SUCCESS';
export const UPDATE_ONE_COMMUNITY_FAIL = 'UPDATE_ONE_COMMUNITY_FAIL';

export const DELETE_ONE_COMMUNITY = 'DELETE_ONE_COMMUNITY';
export const DELETE_ONE_COMMUNITY_SUCCESS = 'DELETE_ONE_COMMUNITY_SUCCESS';
export const DELETE_ONE_COMMUNITY_FAIL = 'DELETE_ONE_COMMUNITY_FAIL';

export const INDEX_STATIONS = 'INDEX_STATIONS';
export const INDEX_STATIONS_SUCCESS = 'INDEX_STATIONS_SUCCESS';
export const INDEX_STATIONS_FAIL = 'INDEX_STATIONS_FAIL';

export const CREATE_ONE_STATION = 'CREATE_ONE_STATION';
export const CREATE_ONE_STATION_SUCCESS = 'CREATE_ONE_STATION_SUCCESS';
export const CREATE_ONE_STATION_FAIL = 'CREATE_ONE_STATION_FAIL';

export const UPDATE_ONE_STATION = 'UPDATE_ONE_STATION';
export const UPDATE_ONE_STATION_SUCCESS = 'UPDATE_ONE_STATION_SUCCESS';
export const UPDATE_ONE_STATION_FAIL = 'UPDATE_ONE_STATION_FAIL';

export const DELETE_ONE_STATION = 'DELETE_ONE_STATION';
export const DELETE_ONE_STATION_SUCCESS = 'DELETE_ONE_STATION_SUCCESS';
export const DELETE_ONE_STATION_FAIL = 'DELETE_ONE_STATION_FAIL';

export const INDEX_ORGANIZATIONS = 'INDEX_ORGANIZATIONS';
export const INDEX_ORGANIZATIONS_SUCCESS = 'INDEX_ORGANIZATIONS_SUCCESS';
export const INDEX_ORGANIZATIONS_FAIL = 'INDEX_ORGANIZATIONS_FAIL';

export const CREATE_ONE_ORGANIZATION = 'CREATE_ONE_ORGANIZATION';
export const CREATE_ONE_ORGANIZATION_SUCCESS = 'CREATE_ONE_ORGANIZATION_SUCCESS';
export const CREATE_ONE_ORGANIZATION_FAIL = 'CREATE_ONE_ORGANIZATION_FAIL';

export const UPDATE_ONE_ORGANIZATION= 'UPDATE_ONE_ORGANIZATION';
export const UPDATE_ONE_ORGANIZATION_SUCCESS = 'UPDATE_ONE_ORGANIZATION_SUCCESS';
export const UPDATE_ONE_ORGANIZATION_FAIL = 'UPDATE_ONE_ORGANIZATION_FAIL';

export const DELETE_ONE_ORGANIZATION = 'DELETE_ONE_ORGANIZATION';
export const DELETE_ONE_ORGANIZATION_SUCCESS = 'DELETE_ONE_ORGANIZATION_SUCCESS';
export const DELETE_ONE_ORGANIZATION_FAIL = 'DELETE_ONE_ORGANIZATION_FAIL';

export const PREPARE_STATE = 'PREPARE_STATE';


export const ALERT = 'ALERT';

